Feature/next sitemap
Kaherdin/tagadart-ts pull request #11
Opened 2024-11-04 05:49 UTC by enjoy-life0000

1. configured the next-sitemap.config.js, 
2. created the route.ts in the app/server-sitemap.xml directory.

2024-11-04 20:28 UTC, Kaherdin requested changes
Not enough, I want a dynamic sitemap ! With subpages too.

Did you read this documentation : https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap and this video : https://www.youtube.com/watch?v=w29phXIag-4&ab_channel=Raddy

Will test more later

2024-11-05 07:20 UTC, enjoy-life0000 commented
> Not enough, I want a dynamic sitemap ! With subpages too.
> 
> Did you read this documentation : https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap and this video : https://www.youtube.com/watch?v=w29phXIag-4&ab_channel=Raddy
> 
> Will test more later

your first solution is to implement the dynamic sitemap package to generate sitemaps dynamically using by next-sitemap.
https://www.notion.so/Dynamic-sitemap-with-next-js-12e11b57ab968040b583c9d2e2473bd4

your second solution is to return an array of sitemap entries using by sitemap.ts manually
https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap

2024-11-05 10:21 UTC, Kaherdin commented
> > Not enough, I want a dynamic sitemap ! With subpages too.
> > Did you read this documentation : https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap and this video : https://www.youtube.com/watch?v=w29phXIag-4&ab_channel=Raddy
> > Will test more later
> 
> your first solution is to implement the dynamic sitemap package to generate sitemaps dynamically using by next-sitemap. https://www.notion.so/Dynamic-sitemap-with-next-js-12e11b57ab968040b583c9d2e2473bd4
> 
> your second solution is to return an array of sitemap entries using by sitemap.ts manually https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap
> 
> we can choose another one solution, using both solutions simultaneously is not advisable and will not improve SEO.

Yes of course, I write you that on chat : 

Thanks for update. Actually i'm looking a next-sitemap and hesitating between next-sitemap and official built-in version of sitemap by next js.

Looking at both options (next-sitemap package vs Next.js's built-in solution), I recommend using Next.js's built-in solution for your case since:

It's simpler to implement
It's officially supported by Next.js
It integrates better with the App Router
No extra dependencies needed

Here's how you could implement it for your Strapi case:

With something like this : 

```
// app/sitemap.ts
import { MetadataRoute } from 'next'
import { fetchAPI } from '@/lib/api' // Your Strapi API utility

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000/'

  // Static routes
  const staticRoutes = [
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: 'yearly' as const,
      priority: 1,
    },
    {
      url: `${baseUrl}/blogs`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/projects`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/contact`,
      lastModified: new Date(),
      changeFrequency: 'yearly' as const,
      priority: 0.5,
    },
    // Add other static routes...
  ]

  // Fetch dynamic data
  const [pages, posts] = await Promise.all([fetchPages(), fetchPosts()])

  // Dynamic pages routes
  const pageRoutes = pages.map((page) => ({
    url: `${baseUrl}/${page.attributes.locale}/${page.attributes.slug}`,
    lastModified: new Date(page.attributes.updatedAt),
    changeFrequency: 'weekly' as const,
    priority: 0.7,
  }))

  // Blog posts routes
  const postRoutes = posts.map((post) => ({
    url: `${baseUrl}/posts/${post.attributes.slug}`,
    lastModified: new Date(post.attributes.updatedAt),
    changeFrequency: 'weekly' as const,
    priority: 0.6,
  }))

  return [...staticRoutes, ...pageRoutes, ...postRoutes]
}
```

Or for next-sitemap (if you think it's better), you can also need to geneate pages dynamicly : 

```
// Process dynamic pages
  const dynamicPageFields: ISitemapField[] = pages.map((page) => ({
    loc: `${baseUrl}/${page.attributes.locale}/${page.attributes.slug}`,
    lastmod: page.attributes.updatedAt,
    changefreq: 'weekly',
    priority: 0.7,
  }));

  // Process blog posts
  const blogPostFields: ISitemapField[] = blogPosts.map((post) => ({
    loc: `${baseUrl}/blog/${post.attributes.slug}`,
    lastmod: post.attributes.updatedAt,
    changefreq: 'weekly',
    priority: 0.6,
  }));

  // Combine static and dynamic fields
  const staticFields: ISitemapField[] = staticPages.map(page => ({
    loc: page.url,
    lastmod: page.lastmod,
    changefreq: 'daily',
    priority: 0.7,
  }));

  const allFields = [...staticFields, ...dynamicPageFields, ...blogPostFields];

  return getServerSideSitemap(allFields);
}
```

2024-11-06 17:09 UTC, Kaherdin approved these changes

2024-11-06 17:09 UTC, merged